trigger:
- master

pool:
  name: Devops-agent

variables:
  sendgrid.api_key: $(SENDGRID_API_KEY) 

steps:
- task: Bash@3
  displayName: 'Send Email Notification via SendGrid'
  inputs:
    targetType: 'inline'
    script: |
      curl --request POST \
      --url https://api.sendgrid.com/v3/mail/send \
      --header "Authorization: Bearer $(sendgrid.api_key)" \
      --header 'Content-Type: application/json' \
      --data '{
        "personalizations": [{
          "to": [{"email": "lakhwindersinghwins@gmail.com"}],
          "subject": "Azure DevOps Notification"
        }],
        "from": {"email": "lakhwindrrsingh1313@gmail.com"},
        "content": [{
          "type": "text/plain",
          "value": "Build completed successfully on Azure DevOps!"
        }]
      }'
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'devops-sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Devops_Devops_AZIivDHA8z0dVIDFaCRS'
    cliProjectName: 'Devops'
    cliSources: '.'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'