trigger:
- master

pool:
  name: Devops-agent

variables:
  sendgrid.api_key: $(SENDGRID_API_KEY) 

steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'devops-sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Devops_Devops_AZIivDHA8z0dVIDFaCRS'
    cliProjectName: 'Devops'
    cliSources: '.'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'

# Task to send SonarQube scan report email notification via SendGrid
- task: Bash@3
  displayName: 'Send SonarQube Scan Report Notification via SendGrid'
  condition: succeeded()  # Send only if previous tasks succeed
  inputs:
    targetType: 'inline'
    script: |
      curl --request POST \
      --url https://api.sendgrid.com/v3/mail/send \
      --header "Authorization: Bearer $(sendgrid.api_key)" \
      --header 'Content-Type: application/json' \
      --data '{
        "personalizations": [{
          "to": [{"email": "lakhwindersinghwins@gmail.com"}],
          "subject": "SonarQube Scan Report - Azure DevOps Pipeline"
        }],
        "from": {"email": "lakhwindrrsingh1313@gmail.com"},
        "content": [{
          "type": "text/plain",
          "value": "The SonarQube scan for project Devops has completed successfully. You can review the scan results on the SonarQube dashboard."
        }]
      }'
