trigger:
- master

pool:
  name: Devops-agent  # Ensure this is a Windows-based agent

steps:
- script: |
    echo "Stopping SonarQube service..."
    net stop SonarQube
    echo "Clearing SonarQube cache..."
    rmdir /S /Q C:\SonarQube\data\web
    echo "Starting SonarQube service..."
    net start SonarQube
    echo "SonarQube cache cleared and service restarted successfully."
  displayName: Clear SonarQube Cache
  condition: always()  # Ensure this step runs even if a previous task fails

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'devops'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'Devops_Devops_AZNxmZ_RwO52hsj8ib-0'
    cliProjectName: 'devops'
    cliSources: '.'

- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '1200'
