trigger:
- master

pool: 
  name: Devops-agent

steps:
- checkout: self
  fetchDepth: 0

- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'ditsdevops'
    organization: 'dits-devops1'
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'
