trigger:
- master

pool:
  name: Devops-agent

steps:
- script: |
    echo "Clearing SonarQube cache..."
    sudo rm -rf /opt/sonarqube/data/web
    echo "Restarting SonarQube service..."
    sudo systemctl restart sonar
    echo "SonarQube cache cleared and service restarted successfully."
  displayName: Clear SonarQube Cache
  condition: always() # Ensure this step runs even if a previous task fails

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'devops'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'Devops_Devops_AZNxmZ_RwO52hsj8ib-0'
    cliProjectName: 'devops'
    cliSources: '.'

- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
    
- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '1200'
