trigger:
  - master

pool:
  vmImage: 'DITS-DevOps'

steps:
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'sonar-qube'
    scannerMode: 'cli'
    configMode: 'file'

- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'