trigger:
- master

pool:
  name: Devops-agent

steps:
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'devops'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'Devops_Devops_AZNxmZ_RwO52hsj8ib-0'
    cliProjectName: 'devops'
    cliSources: '.'

- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
    
- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '1200'
