name: SonarQube Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Ensure this secret is set in your repository settings
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # Ensure this secret is set in your repository settings
